FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем файлы проекта и тесты
COPY alembic alembic
COPY alembic.ini alembic.ini
COPY app app
COPY tests tests

# Команда запуска тестов
CMD ["pytest", "tests"]
